## These are some examples from the website
- https://faculty.washington.edu/otoomet/machinelearning-py/numpy-and-pandas.html

### Setup Numpy

In [2]:
import numpy as np

### NumPy Array
 - Create an array a with 6 elements, single row
 - Create an array b with 2 lists

In [ ]:
a = np.array([0,1,2,3,4,5])

a 

In [5]:
b = np.array([[0,1,2],[3,4,5]])

b 

[[0 1 2]
 [3 4 5]]


### Find out shapes of above arrays

In [11]:
# Shape of a 
np.shape(a)

(6,)

In [12]:
# Shape of b
np.shape(b)

(2, 3)

### Reshape (change the shape) of above arrays

In [14]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b.reshape(6,)

array([0, 1, 2, 3, 4, 5])

### Creating arrays using computation
- define the range and create a numpy vector
- define an array with zeros and ones
- do simple mathematical operations like, multiplication, summation and deductions

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Now apply reshape function on array arange function

In [18]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
# Create a numpy array intialized as zero

c = np.zeros(10).reshape(5,2)

In [22]:
# Create a numpy array initialized as ones

d = np.ones(10).reshape(5,2)

In [23]:
# Do a mathematical operation to get a -1 using above arrays

np.array(c - d)

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [24]:
# Do a mathematical operation to get zeros in the resulting arrays

np.array(c*d)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Do a mathematical operation to sum both arrays

np.array(d+d)

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [4]:
# Create an array of even numbers

np.arange(20).reshape(4,5)

# Now make this a even number series by multiplying by 2

2*np.arange(20).reshape(4,5)

# Now add to get the final matrix

2 + 2*np.arange(20).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [5]:
# Compare values and their results are in boolean

a = np.arange(12).reshape(3,4)

print(a)

print("\n")

b = a > 6

print(b)
print("\n")

a == 7

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[False False False False]
 [False False False  True]
 [ True  True  True  True]]




array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

### Array Indexing and position based element extraction

In [8]:
# Create an array and print elements based on their positions

a = np.arange(12)

# Extract 4th till 8th element

a[3:7]


array([3, 4, 5, 6])

In [12]:
# First print the value of array a
# Reassign elements to some random values from 4th till 8th element

print(a)

print("\n")

a[3:7] = -1


[ 0  1  2 -1 -1 -1 -1  7  8  9 10 11]




In [10]:
# create another array and make it 2 dimensional matrix

twoD = np.arange(12).reshape(3,4)
print(twoD)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# Get all rows. Need to be careful when extracting with and without colon
# Without colon, index starts with 0
print(twoD[1])

# With Colon, behaviour is diffetent 

print(twoD[0:1])

[4 5 6 7]
[[0 1 2 3]]


#### Exercise
- Create matrix and access rows and columns
- create a 4x5 array of even numbers: 10, 12, 14, …
- extract third column
- set the fourth row to 1,2,3,4,5

In [ ]:
# Create an array of even numbers

a = np.arange(20).reshape(4,5)

# Make this even number matrix

b = 2*a

# Add 10 to make this matrix as per exercise

b = 10 + 2*a

print(b)
# Extract third column

b[:,2]

# Set the fourth row to 1,2,3,4,5

b[3,] = [1,2,3,4,5]

print(b)


### Array indexing and logical extraction
- a logical argument can be inputted to extract elements that meet the conditions, can also be replaced with other values
- 2 arrays need not to be related and index from one vector can be used to extract elements from another

In [25]:
# Create an array and extract elements greater than 5
a = np.array([1,2,7,8])

a[a > 5]

array([7, 8])

In [27]:
# Demo extraction of elements from 1 vector based on index received from another vector

names = np.array(["Ram", "Shayam", "Seeta", "Geeta", "Kumar", "Ram"])

results = np.array([15, 17, 19, 20, 21, 22])

# Now extract Ram's score from results vector

results[names == "Ram"]

array([15, 22])

In [32]:
# As above but now results are 2D matrix

names = np.array(["Ram", "Shayam", "Seeta", "Geeta", "Kumar", "Ram"])

results = np.array([[15, 20], [17, 20], [19, 30], [20, 32], [21, 12], [22, 12]])

print(results)

# Now extract results for Ram, here need to check the syntex as it is with comma and working without that too

results[names == "Ram"]


[[15 20]
 [17 20]
 [19 30]
 [20 32]
 [21 12]
 [22 12]]


array([[15, 20],
       [22, 12]])

In [44]:
# Not use logical extraction and replace value. Create a matrix with random value
# Run operations in next cell as a random number matrix is generated

a = np.random.randn(12).reshape(3,4)

print(a)


[[-0.02267741  2.44226472 -1.02040764 -0.94448131]
 [ 0.91663937  1.81083896  1.35332056  0.82896562]
 [-2.80571926  1.25414656 -2.15772491 -0.07215166]]


In [45]:
# Replace all negative values with 0

a[a < 0] = 0

print(a)

[[0.         2.44226472 0.         0.        ]
 [0.91663937 1.81083896 1.35332056 0.82896562]
 [0.         1.25414656 0.         0.        ]]


In [47]:
# now replace all positive values with 1, 2, 3 and so on but vector length should be same

a[a > 0] = [1, 2, 3, 4, 5, 6]

print(a)

[[0. 1. 0. 0.]
 [2. 3. 4. 5.]
 [0. 6. 0. 0.]]
